export const results = [
  {
    name: "הליכוד בהנהגת בנימין נתניהו לראשות הממשלה",
    letters: "מחל",
    mandatim: 35,
    odafim: "טב",
    percent: "26.46%",
    amount: 1140370,
  },
  {
    name: "כחול לבן בראשות בני גנץ ויאיר לפיד",
    letters: "פה",
    mandatim: 35,
    percent: "26.13%",
    amount: 1125881,
  },
  {
    name: 'התאחדות הספרדים שומרי התורה תנועתו של מרן הרב עובדיה יוסף זצ"ל',
    letters: "שס",
    mandatim: 8,
    odafim: "ג",
    percent: "5.99%",
    amount: 258275,
  },
  {
    name: "יהדות התורה והשבת אגודת ישראל - דגל התורה",
    letters: "ג",
    mandatim: 8,
    odafim: "שס",
    percent: "5.78%",
    amount: 249049,
  },
  {
    name: 'חד"ש תע"ל בראשות איימן עודה ואחמד טיבי',
    letters: "ום",
    mandatim: 6,
    odafim: "דעם",
    percent: "4.49%",
    amount: 193442,
  },
  {
    name: "מפלגת העבודה בראשות אבי גבאי",
    letters: "אמת",
    odafim: "מרצ",
    mandatim: 6,
    percent: "4.43%",
    amount: 190870,
  },
  {
    name: "ישראל ביתנו",
    letters: "ל",
    mandatim: 5,
    odafim: "נ",
    percent: "4.01%",
    amount: 173004,
  },
  {
    name: "איחוד מפלגות הימין הבית היהודי-האיחוד הלאומי- עוצמה יהודית",
    letters: "טב",
    odafim: "מחל",
    mandatim: 5,
    percent: "3.70%",
    amount: 159468,
  },
  {
    name: "מרצ- השמאל של ישראל",
    letters: "מרצ",
    mandatim: 4,
    odafim: "אמת",
    percent: "3.63%",
    amount: 156473,
  },
  {
    name: "כולנו הימין השפוי בראשות משה כחלון",
    letters: "כ",
    mandatim: 4,
    percent: "3.54%",
    amount: 152756,
  },
  {
    name: 'רע"ם-בל"ד הרשימה הערבית המאוחדת ברית לאומית דמוקרטית',
    letters: "דעם",
    odafim: "ום",
    mandatim: 4,
    percent: "3.33%",
    amount: 143666,
  },
  {
    name: "הימין החדש בראשות שקד ובנט",
    letters: "נ",
    odafim: "ל",
    mandatim: 0,
    percent: "3.22%",
    amount: 138598,
  },
  {
    name: "זהות - תנועה ישראלית יהודית בהנהגת משה פייגלין",
    letters: "ז",
    mandatim: 0,
    percent: "2.74%",
    amount: 118031,
  },
  {
    name: "גשר בראשות אורלי לוי אבקסיס",
    letters: "נר",
    mandatim: 0,
    percent: "1.73%",
    amount: 74701,
  },
  {
    name: 'בט"ח-ביטחון חברתי בראשות סמיון גרפמן',
    letters: "ן",
    mandatim: 0,
    percent: "0.11%",
    amount: 4618,
  },
  {
    name: "הרשימה הערבית בראשות מוחמד כנעאן",
    letters: "ר",
    mandatim: 0,
    percent: "0.10%",
    amount: 4135,
  },
  {
    name: "צדק חברתי",
    letters: "צק",
    mandatim: 0,
    percent: "0.09%",
    amount: 3843,
  },
  {
    name: "מגן בראשות גל הירש",
    letters: "נץ",
    mandatim: 0,
    percent: "0.08%",
    amount: 3394,
  },
  {
    name: "צדק לכל כי הגיעה העת למען החי.האדם.והאדמה",
    letters: "ק",
    mandatim: 0,
    percent: "0.08%",
    amount: 3281,
  },
  {
    name: 'אורן חזן בראשות "צומת"',
    letters: "זץ",
    mandatim: 0,
    percent: "0.06%",
    amount: 2417,
  },
  {
    name: "ישר - דמוקרטיה אמיתית",
    letters: "י",
    mandatim: 0,
    percent: "0.03%",
    amount: 1438,
  },
  {
    name: "זכויותינו בקולנו",
    letters: "נז",
    mandatim: 0,
    percent: "0.03%",
    amount: 1316,
  },
  {
    name: "מפלגת האזרחים הוותיקים",
    letters: "זי",
    mandatim: 0,
    percent: "0.03%",
    amount: 1168,
  },
  {
    name: "כל ישראל אחים ופעולה לישראל",
    letters: "קף",
    mandatim: 0,
    percent: "0.03%",
    amount: 1140,
  },
  {
    name: "הפיראטים בראשות האינטרנט פתק לשלשול",
    letters: "ףז",
    mandatim: 0,
    odafim: "ףץ",
    percent: "0.02%",
    amount: 819,
  },
  {
    name: "פשוט אהבה - כי כולן/ם בני אדם",
    letters: "ףי",
    mandatim: 0,
    percent: "0.02%",
    amount: 733,
  },
  {
    name: "ארץ ישראל שלנו",
    letters: "קי",
    mandatim: 0,
    percent: "0.02%",
    amount: 701,
  },
  {
    name: "נ נח - הרשימה הממלכתית - תרימו את הראש",
    letters: "ףץ",
    mandatim: 0,
    odafim: "ףז",
    percent: "0.01%",
    amount: 624,
  },
  {
    name: "מהתחלה",
    letters: "קן",
    mandatim: 0,
    percent: "0.01%",
    amount: 603,
  },
  {
    name: "התקווה לשינוי",
    letters: "ךק",
    mandatim: 0,
    percent: "0.01%",
    amount: 562,
  },
  {
    name: "כלכלה ירוקה -מדינה אחת",
    letters: "ץ",
    mandatim: 0,
    percent: "0.01%",
    amount: 556,
  },
  {
    name: "חינוך",
    letters: "ףך",
    mandatim: 0,
    percent: "0.01%",
    amount: 518,
  },
  {
    name: "אחריות למייסדים בראשות חיים דיין",
    letters: "יץ",
    mandatim: 0,
    percent: "0.01%",
    amount: 428,
  },
  {
    name: "כבוד האדם",
    letters: "ןך",
    mandatim: 0,
    percent: "0.01%",
    amount: 404,
  },
  {
    name: "שווים",
    letters: "ףנ",
    mandatim: 0,
    percent: "0.01%",
    amount: 401,
  },
  {
    name: "מנהיגות חברתית",
    letters: "ןנ",
    mandatim: 0,
    percent: "0.01%",
    amount: 385,
  },
  {
    name: "אני ואתה-מפלגת העם הישראלית בהובלת דר' אלון גלעדי",
    letters: "ץי",
    mandatim: 0,
    percent: "0.01%",
    amount: 368,
  },
  {
    name: 'מפלגת הגוש התנ"כי',
    letters: "יז",
    mandatim: 0,
    percent: "0.01%",
    amount: 353,
  },
  {
    name: "איחוד בני הברית בראשות רב חובל בשארה שליאן",
    letters: "ין",
    mandatim: 0,
    percent: "0.01%",
    amount: 265,
  },
  {
    name: "ברית עולם",
    letters: "זך",
    mandatim: 0,
    percent: "0.01%",
    amount: 216,
  },
  {
    name: "אופק חדש בכבוד",
    letters: "ץז",
    mandatim: 0,
    percent: "0.00%",
    amount: 0,
  },
  {
    name: "יחד בראשות אלי ישי",
    letters: "זנ",
    mandatim: 0,
    percent: "0.00%",
    amount: 0,
  },
  {
    name: "מפלגת הרפורמה",
    letters: "נך",
    mandatim: 0,
    percent: "0.00%",
    amount: 0,
  },
];
