export const results = [
  {
    name: "הליכוד בהנהגת בנימין נתניהו לראשות הממשלה",
    letters: "מחל",
    odafim: "ט",
    mandatim: 30,
    percent: "24.19%",
    amount: 1066892,
  },
  {
    name: "יש עתיד בראשות יאיר לפיד",
    letters: "פה",
    odafim: "ל",
    mandatim: 17,
    percent: "13.93%",
    amount: 614112,
  },
  {
    name: 'התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ"ל',
    letters: "שס",
    odafim: "ג",
    mandatim: 9,
    percent: "7.17%",
    amount: 316008,
  },
  {
    name: "כחול לבן בראשות בני גנץ",
    letters: "כן",
    odafim: "יז",
    mandatim: 8,
    percent: "6.63%",
    amount: 292257,
  },
  {
    name: "ימינה בראשות נפתלי בנט",
    letters: "ב",
    odafim: "ת",
    mandatim: 7,
    percent: "6.21%",
    amount: 273836,
  },
  {
    name: "מפלגת העבודה בראשות מרב מיכאלי",
    letters: "אמת",
    odafim: "מרצ",
    mandatim: 7,
    percent: "6.09%",
    amount: 268767,
  },
  {
    name: "יהדות התורה והשבת אגודת ישראל – דגל התורה",
    letters: "ג",
    odafim: "שס",
    mandatim: 7,
    percent: "5.63%",
    amount: 248391,
  },
  {
    name: "ישראל ביתנו בראשות אביגדור ליברמן",
    letters: "ל",
    odafim: "פה",
    mandatim: 7,
    percent: "5.63%",
    amount: 248370,
  },
  {
    name: "הציונות הדתית בראשות בצלאל סמוטריץ'",
    letters: "ט",
    odafim: "מחל",
    mandatim: 6,
    percent: "5.12%",
    amount: 225641,
  },
  {
    name: 'הרשימה המשותפת (חד"ש, תע"ל, בל"ד)',
    letters: "ודעם",
    mandatim: 6,
    percent: "4.82%",
    amount: 212583,
  },
  {
    name: "תקווה חדשה בהנהגת גדעון סער לראשות הממשלה",
    letters: "ת",
    odafim: "ב",
    mandatim: 6,
    percent: "4.74%",
    amount: 209161,
  },
  {
    name: "מרצ – השמאל של ישראל",
    letters: "מרצ",
    odafim: "אמת",
    mandatim: 6,
    percent: "4.59%",
    amount: 202218,
  },
  {
    name: "הרשימה הערבית המאוחדת",
    letters: "עם",
    mandatim: 4,
    percent: "3.79%",
    amount: 167064,
  },
  {
    name: "הכלכלית החדשה בראשות פרופסור ירון זליכה",
    letters: "יז",
    odafim: "כן",
    mandatim: 0,
    percent: "0.79%",
    amount: 34883,
  },
  {
    name: "רפא – רק בריאות בראשות דוקטור אריה אבני",
    letters: "ר",
    mandatim: 0,
    percent: "0.39%",
    amount: 17346,
  },
  {
    name: "הפיראטים",
    letters: "ףז",
    mandatim: 0,
    percent: "0.03%",
    amount: 1309,
  },
  {
    name: "אני ואתה – מפלגת העם הישראלית",
    letters: "כך",
    mandatim: 0,
    percent: "0.03%",
    amount: 1291,
  },
  {
    name: "התקווה לשינוי",
    letters: "רנ",
    mandatim: 0,
    percent: "0.03%",
    amount: 1189,
  },
  {
    name: "המפץ החברתי - גימלאים",
    letters: "י",
    mandatim: 0,
    percent: "0.02%",
    amount: 811,
  },
  {
    name: "משפט צדק, לרפורמה במערכת המשפט",
    letters: "קץ",
    mandatim: 0,
    percent: "0.02%",
    amount: 729,
  },
  {
    name: "צומת – עצמאים, חקלאים, כפרים",
    letters: "זץ",
    mandatim: 0,
    percent: "0.02%",
    amount: 663,
  },
  {
    name: "מפלגת עם שלם – בראשות הרב חיים אמסלם",
    letters: "רף",
    mandatim: 0,
    percent: "0.01%",
    amount: 592,
  },
  {
    name: 'סדר חדש לשינוי שיטת הבחירות והממשל בישראל בראשות עו"ד אביטל אופק',
    letters: "קך",
    mandatim: 0,
    percent: "0.01%",
    amount: 514,
  },
  {
    name: 'קמ"ה – קידום מעמד הפרט',
    letters: "נ",
    mandatim: 0,
    percent: "0.01%",
    amount: 486,
  },
  {
    name: "נועם קולמן, לירון עופרי וסולי וולף הבלתי אפשרי, אפשרי",
    letters: "ק",
    mandatim: 0,
    percent: "0.01%",
    amount: 463,
  },
  {
    name: "הלב היהודי בראשות אלי יוסף",
    letters: "כ",
    mandatim: 0,
    percent: "0.01%",
    amount: 443,
  },
  {
    name: "עצמנו עצמאים וליברלים",
    letters: "צי",
    mandatim: 0,
    percent: "0.01%",
    amount: 441,
  },
  {
    name: 'מפלגת הגוש התנ"כי',
    letters: "יק",
    mandatim: 0,
    percent: "0.01%",
    amount: 429,
  },
  {
    name: "עולם חדש בראשות יורם אדרי",
    letters: "ני",
    mandatim: 0,
    percent: "0.01%",
    amount: 429,
  },
  {
    name: "ברית השותפות לאיחוד לאומי בהנהגת רב חובל ב. שליאן",
    letters: "ינ",
    mandatim: 0,
    percent: "0.01%",
    amount: 408,
  },
  {
    name: "הישראלים",
    letters: "ז",
    mandatim: 0,
    percent: "0.01%",
    amount: 395,
  },
  {
    name: "מפלגת שמע בראשות נפתלי גולדמן",
    letters: "קי",
    mandatim: 0,
    percent: "0.01%",
    amount: 395,
  },
  {
    name: "דעם – כלכלה ירוקה מדינה אחת",
    letters: "ץ",
    mandatim: 0,
    percent: "0.01%",
    amount: 385,
  },
  {
    name: "מנהיגות חברתית",
    letters: "יר",
    mandatim: 0,
    percent: "0.01%",
    amount: 256,
  },
  {
    name: "מען (יחד) לעידן חדש",
    letters: "צכ",
    mandatim: 0,
    percent: "0.01%",
    amount: 253,
  },
  {
    name: "חץ",
    letters: "צף",
    mandatim: 0,
    percent: "0.01%",
    amount: 226,
  },
  {
    name: '"אנחנו" – בראשות עו"ד מוש חוג\'ה',
    letters: "נר",
    mandatim: 0,
    percent: "0.00%",
    amount: 220,
  },
  {
    name: "כבוד האדם, בראשות עו\"ד ארקדי פוגץ'",
    letters: "יף",
    mandatim: 0,
    percent: "0.00%",
    amount: 196,
  },
  {
    name: "דמוקרטית – חירות, שיוויון וערבות הדדית",
    letters: "רק",
    mandatim: 0,
    percent: "0.00%",
    amount: 0,
  },
];

export const metaData = {
  citizents: 6578084,
  votes: 4436365,
  percent: "67.44%",
  kosherVotes: 4410052,
  treifVotes: 26313,
};
