export const results = [
  {
    name: "כחול לבן - בראשות בני גנץ ויאיר לפיד",
    letters: "פה",
    mandatim: 33,
    odafim: "ל",
    percent: "25.95%",
    amount: 1151214,
  },
  {
    name: "הליכוד בהנהגת בנימין נתניהו לראשות הממשלה",
    letters: "מחל",
    mandatim: 32,
    odafim: "טב",
    percent: "25.10%",
    amount: 1113617,
  },
  {
    name: 'הרשימה המשותפת חד"ש, רע"ם, תע"ל, בל"ד',
    letters: "ודעם",
    mandatim: 13,
    percent: "10.60%",
    amount: 470211,
  },
  {
    name: 'התאחדות הספרדים שומרי התורה תנועתו של מרן הרב עובדיה יוסף זצ"ל',
    letters: "שס",
    mandatim: 9,
    odafim: "ג",
    percent: "7.44%",
    amount: 330199,
  },
  {
    name: "ישראל ביתנו בראשות אביגדור ליברמן",
    letters: "ל",
    mandatim: 8,
    odafim: "פה",
    percent: "6.99%",
    amount: 310154,
  },
  {
    name: "יהדות התורה והשבת אגודת ישראל - דגל התורה",
    letters: "ג",
    mandatim: 7,
    odafim: "שס",
    percent: "6.06%",
    amount: 268775,
  },
  {
    name: "ימינה בראשות איילת שקד הבית היהודי-האיחוד הלאומי-הימין החדש",
    letters: "טב",
    mandatim: 7,
    odafim: "מחל",
    percent: "5.87%",
    amount: 260655,
  },
  {
    name: "העבודה - גשר בראשות עמיר פרץ ואורלי לוי אבקסיס",
    letters: "אמת",
    mandatim: 6,
    odafim: "מרצ",
    percent: "4.80%",
    amount: 212782,
  },
  {
    name: "המחנה הדמוקרטי בהנהגת הורוביץ, שפיר וברק",
    letters: "מרצ",
    mandatim: 5,
    odafim: "אמת",
    percent: "4.34%",
    amount: 192495,
  },
  {
    name: "עוצמה יהודית בראשות איתמר בן גביר",
    letters: "כף",
    mandatim: 0,
    percent: "1.88%",
    amount: 83609,
  },
  {
    name: "צומת - התיישבות וחקלאות",
    letters: "זץ",
    mandatim: 0,
    percent: "0.33%",
    amount: 14805,
  },
  {
    name: "האחדות העממית - אלוחדה אלשעביה בראשות פרופ' אסעד גאנם",
    letters: "כי",
    mandatim: 0,
    percent: "0.13%",
    amount: 5946,
  },
  {
    name: "אדום לבן - לגליזציה לקנביס, שוויון לאתיופים, ערבים ומקופחים",
    letters: "יז",
    mandatim: 0,
    percent: "0.10%",
    amount: 4358,
  },
  {
    name: "צדק בראשות אבי ילאו",
    letters: "צ",
    mandatim: 0,
    percent: "0.07%",
    amount: 3053,
  },
  {
    name: "רון קובי - הימין החילוני נלחמים בכפיה החרדית",
    letters: "רק",
    mandatim: 0,
    percent: "0.05%",
    amount: 2395,
  },
  {
    name: "כבוד ושוויון",
    letters: "נך",
    mandatim: 0,
    percent: "0.03%",
    amount: 1545,
  },
  {
    name: "זכויותינו בקולנו - לחיים בכבוד",
    letters: "ק",
    mandatim: 0,
    percent: "0.03%",
    amount: 1473,
  },
  {
    name: "הפיראטים - כי כולנו באותה סירה והכל אותו שייט",
    letters: "ףז",
    mandatim: 0,
    percent: "0.03%",
    amount: 1236,
  },
  {
    name: "עוצמה כלכלית קולם של העסקים בישראל",
    letters: "ז",
    mandatim: 0,
    percent: "0.03%",
    amount: 1193,
  },
  {
    name: "מתקדמת",
    letters: "נ",
    mandatim: 0,
    percent: "0.02%",
    amount: 1033,
  },
  {
    name: 'קמ"ה - קידום מעמד הפרט',
    letters: "קץ",
    mandatim: 0,
    percent: "0.02%",
    amount: 994,
  },
  {
    name: "סדר חדש - לשינוי שיטת הבחירות",
    letters: "קך",
    mandatim: 0,
    percent: "0.02%",
    amount: 928,
  },
  {
    name: "מפלגת הדמוקראטורה",
    letters: "זכ",
    mandatim: 0,
    percent: "0.02%",
    amount: 736,
  },
  {
    name: "צפון",
    letters: "צן",
    mandatim: 0,
    percent: "0.02%",
    amount: 725,
  },
  {
    name: "התנועה הנוצרית הליבראלית",
    letters: "ינ",
    mandatim: 0,
    percent: "0.01%",
    amount: 610,
  },
  {
    name: "דעם - כלכלה ירוקה מדינה אחת",
    letters: "ץ",
    mandatim: 0,
    percent: "0.01%",
    amount: 592,
  },
  {
    name: "כבוד האדם",
    letters: "יף",
    mandatim: 0,
    percent: "0.01%",
    amount: 542,
  },
  {
    name: 'מפלגת הגוש התנ"כי',
    letters: "יק",
    mandatim: 0,
    percent: "0.01%",
    amount: 497,
  },
  {
    name: "מנהיגות חברתית",
    letters: "י",
    mandatim: 0,
    percent: "0.01%",
    amount: 434,
  },
  {
    name: "זהות - תנועה ישראלית יהודית בהנהגת משה פייגלין",
    letters: "זן",
    mandatim: 0,
    percent: "0.00%",
    amount: 0,
  },
  {
    name: "כל ישראל אחים לשוויון חברתי",
    letters: "נץ",
    mandatim: 0,
    percent: "0.00%",
    amount: 0,
  },
  {
    name: "נעם - עם נורמלי בארצנו",
    letters: "כ",
    mandatim: 0,
    percent: "0.00%",
    amount: 0,
  },
];
