export const results = [
  {
    name: "הליכוד בהנהגת בנימין נתניהו לראשות הממשלה",
    letters: "מחל",
    odafim: "טב",
    mandatim: 36,
    percent: "29.46%",
    amount: 1352449,
  },
  {
    name: "כחול לבן בראשות בני גנץ",
    letters: "פה",
    mandatim: 33,
    odafim: "אמת",
    percent: "26.59%",
    amount: 1220381,
  },
  {
    name: 'הרשימה המשותפת חד"ש, רע"מ, תע"ל, בל"ד',
    letters: "ודעם",
    mandatim: 15,
    percent: "12.67%",
    amount: 581507,
  },
  {
    name: 'התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ"ל',
    letters: "שס",
    mandatim: 9,
    odafim: "ג",
    percent: "7.69%",
    amount: 352853,
  },
  {
    name: "יהדות התורה והשבת אגודת ישראל - דגל התורה",
    letters: "ג",
    mandatim: 7,
    odafim: "שס",
    percent: "5.98%",
    amount: 274437,
  },
  {
    name: "העבודה - גשר - מרצ",
    letters: "אמת",
    mandatim: 7,
    odafim: "פה",
    percent: "5.83%",
    amount: 267480,
  },
  {
    name: "ישראל ביתנו בראשות אביגדור ליברמן",
    letters: "ל",
    mandatim: 7,
    percent: "5.74%",
    amount: 263365,
  },
  {
    name: "ימינה הימין החדש – הבית היהודי – האיחוד הלאומי",
    letters: "טב",
    mandatim: 6,
    odafim: "מחל",
    percent: "5.24%",
    amount: 240689,
  },
  {
    name: "עוצמה יהודית בראשות איתמר בן גביר",
    letters: "נץ",
    mandatim: 0,
    percent: "0.42%",
    amount: 19402,
  },
  {
    name: "עוצמה ליברלית – כלכלית בראשות גלעד אלפר",
    letters: "ז",
    mandatim: 0,
    percent: "0.08%",
    amount: 3781,
  },
  {
    name: "קול הנשים",
    letters: "נ",
    mandatim: 0,
    percent: "0.06%",
    amount: 2773,
  },
  {
    name: "הפיראטים לדמוקרטיה לחצו כאן",
    letters: "ףז",
    mandatim: 0,
    percent: "0.03%",
    amount: 1473,
  },
  {
    name: 'משפט צדק, בראשות ד"ר לריסה עמיר',
    letters: "קץ",
    mandatim: 0,
    percent: "0.03%",
    amount: 1375,
  },
  {
    name: "ישראליסט זכויותינו בקולנו לחיות טוב יותר",
    letters: "ק",
    mandatim: 0,
    percent: "0.02%",
    amount: 980,
  },
  {
    name: "אני ואתה – מפלגת העם הישראלית",
    letters: "כן",
    mandatim: 0,
    percent: "0.02%",
    amount: 812,
  },
  {
    name: "איחוד הברית והשותפות",
    letters: "ינ",
    mandatim: 0,
    percent: "0.01%",
    amount: 677,
  },
  {
    name: 'סדר חדש לשינוי שיטת הבחירות בראשות עו"ד אביטל אופק',
    letters: "קך",
    mandatim: 0,
    percent: "0.01%",
    amount: 677,
  },
  {
    name: "הכח להשפיע למען הציבור לחיות בכבוד",
    letters: "נז",
    mandatim: 0,
    percent: "0.01%",
    amount: 667,
  },
  {
    name: "מתקדמת (בשיתוף עם תנועת הדרור העברי)",
    letters: "נק",
    mandatim: 0,
    percent: "0.01%",
    amount: 622,
  },
  {
    name: "דעם כלכלה ירוקה מדינה אחת",
    letters: "ץ",
    mandatim: 0,
    percent: "0.01%",
    amount: 612,
  },
  {
    name: "הלב היהודי בראשות אלי יוסף",
    letters: "כ",
    mandatim: 0,
    percent: "0.01%",
    amount: 516,
  },
  {
    name: "שמע בראשות נפתלי גולדמן",
    letters: "קי",
    mandatim: 0,
    percent: "0.01%",
    amount: 442,
  },
  {
    name: 'מפלגת הגוש התנ"כי',
    letters: "יק",
    mandatim: 0,
    percent: "0.01%",
    amount: 389,
  },
  {
    name: 'קמ"ה – קידום מעמד הפרט',
    letters: "ני",
    mandatim: 0,
    percent: "0.01%",
    amount: 350,
  },
  {
    name: "אדום לבן – ח'ירבת דוראן בראשות עמי פינשטיין מחכים למשיח? משיח כבר כאן...",
    letters: "יז",
    mandatim: 0,
    percent: "0.01%",
    amount: 342,
  },
  {
    name: "החזון בראשות ציון אלון",
    letters: "י",
    mandatim: 0,
    percent: "0.01%",
    amount: 308,
  },
  {
    name: "מנהיגות חברתית",
    letters: "יר",
    mandatim: 0,
    percent: "0.01%",
    amount: 271,
  },
  {
    name: "כבוד האדם, בראשות עו\"ד ארקדי פוגץ'",
    letters: "יף",
    mandatim: 0,
    percent: "0.00%",
    amount: 222,
  },
  {
    name: "פעולה לישראל",
    letters: "זך",
    mandatim: 0,
    percent: "0.00%",
    amount: 210,
  },
  {
    name: "צומת התנועה לציונות מתחדשת",
    letters: "זץ",
    mandatim: 0,
    percent: "0.00%",
    amount: 0,
  },
];
