export const results = [
  {
    letters: "אמת",
    name: "מפלגת העבודה בראשות מרב מיכאלי",
    mandatim: 0,
    odafim: "מרצ",
    percent: "0%",
    amount: 145540,
  },
  {
    letters: "אצ",
    name: "חופש כלכלי בראשות אביר קארה",
    mandatim: 0,
    percent: "0%",
    amount: 11668,
  },
  {
    letters: "ב",
    name: "הבית היהודי בראשות איילת שקד",
    mandatim: 0,
    percent: "0%",
    amount: 47555,
  },
  {
    letters: "ג",
    name: "יהדות התורה והשבת אגודת ישראל – דגל התורה",
    mandatim: 0,
    percent: "0%",
    odafim: "שס",
    amount: 252662,
  },
  {
    letters: "ד",
    name: "בל\"ד - אלתג'מוע אלווטני אלדמוקרטי בראשות סמי אבו שחאדה",
    mandatim: 0,
    percent: "0%",
    amount: 124095,
  },
  {
    letters: "ום",
    name: 'חד"ש תע"ל בראשות איימן עודה ואחמד טיבי',
    mandatim: 0,
    percent: "0%",
    amount: 159457,
  },
  {
    letters: "ז",
    name: "שחר כוח חברתי בראשות וג'די טאהר",
    mandatim: 0,
    percent: "0%",
    amount: 463,
  },
  {
    letters: "זך",
    name: 'קמ"ה – קידום מעמד הפרט',
    mandatim: 0,
    percent: "0%",
    amount: 181,
  },
  {
    letters: "זץ",
    name: "צומת בראשות משה גרין דרכו של רפול",
    mandatim: 0,
    percent: "0%",
    amount: 325,
  },
  {
    letters: "ט",
    name: "הציונות הדתית בראשות בצלאל סמוטריץ' ועוצמה יהודית בראשות איתמר בן גביר",
    mandatim: 0,
    percent: "0%",
    odafim: "מחל",
    amount: 420849,
  },
  {
    letters: "י",
    name: "ישראל חופשית דמוקרטית בראשות אלי אבידר",
    mandatim: 0,
    percent: "0%",
    amount: 967,
  },
  {
    letters: "יז",
    name: "הכלכלית החדשה בראשות פרופסור ירון זליכה",
    mandatim: 0,
    percent: "0%",
    amount: 11504,
  },
  {
    letters: "ינ",
    name: "איחוד בני הברית – בראשות רב חובל בשארה שליאן",
    mandatim: 0,
    percent: "0%",
    amount: 194,
  },
  {
    letters: "יץ",
    name: "צו השעה",
    mandatim: 0,
    percent: "0%",
    amount: 222,
  },
  {
    letters: "יק",
    name: 'מפלגת הגוש התנ"כי',
    mandatim: 0,
    percent: "0%",
    amount: 376,
  },
  {
    letters: "ך",
    name: "אני ואתה",
    mandatim: 0,
    percent: "0%",
    amount: 1136,
  },
  {
    letters: "כן",
    name: "המחנה הממלכתי בהנהגת בני גנץ לראשות הממשלה",
    mandatim: 0,
    odafim: "פה",
    percent: "0%",
    amount: 363759,
  },
  {
    letters: "ל",
    name: "ישראל ביתנו בראשות אביגדור ליברמן",
    mandatim: 0,
    percent: "0%",
    amount: 176695,
  },
  {
    letters: "מחל",
    name: "הליכוד בהנהגת בנימין נתניהו לראשות הממשלה",
    mandatim: 0,
    percent: "0%",
    odafim: "ט",
    amount: 947795,
  },
  {
    letters: "מרצ",
    name: "מרצ השמאל של ישראל בראשות זהבה גלאון",
    mandatim: 0,
    odafim: "אמת",
    percent: "0%",
    amount: 130599,
  },
  {
    letters: "נז",
    name: "כבוד האדם, בראשות עו\"ד ארקדי פוגץ'",
    mandatim: 0,
    percent: "0%",
    amount: 471,
  },
  {
    letters: "ני",
    name: "נתיב – נחיה תמיד יחד בכבוד",
    mandatim: 0,
    percent: "0%",
    amount: 1151,
  },
  {
    letters: "נף",
    name: "מפלגת שמע בראשות נפתלי גולדמן",
    mandatim: 0,
    percent: "0%",
    amount: 224,
  },
  {
    letters: "נץ",
    name: "העצמאים החדשים בראשות יורם מועלמי",
    mandatim: 0,
    percent: "0%",
    amount: 875,
  },
  {
    letters: "נק",
    name: "יש כיוון בראשות עמוס דב סילבר",
    mandatim: 0,
    percent: "0%",
    amount: 898,
  },
  {
    letters: "נר",
    name: '"אנחנו" - בראשות עו"ד מוש חוג\'ה',
    mandatim: 0,
    percent: "0%",
    amount: 353,
  },
  {
    letters: "עם",
    name: "הרשימה הערבית המאוחדת",
    mandatim: 0,
    percent: "0%",
    amount: 176690,
  },
  {
    letters: "ף",
    name: "הפיראטים - הכי טוב לדעתי אני רוצה להיות שם",
    mandatim: 0,
    percent: "0%",
    amount: 1127,
  },
  {
    letters: "פה",
    name: "יש עתיד בראשות יאיר לפיד לראשות הממשלה",
    mandatim: 0,
    odafim: "כן",
    percent: "0%",
    amount: 730869,
  },
  {
    letters: "ץ",
    name: "מנהיגות חברתית",
    mandatim: 0,
    percent: "0%",
    amount: 841,
  },
  {
    letters: "צ",
    name: "צעירים בוערים בהנהגת הדר מוכתר",
    mandatim: 0,
    percent: "0%",
    amount: 6332,
  },
  {
    letters: "ק",
    name: "קול הסביבה והחי",
    mandatim: 0,
    percent: "0%",
    amount: 1288,
  },
  {
    letters: "קי",
    name: "הלב היהודי בראשות אלי יוסף",
    mandatim: 0,
    percent: "0%",
    amount: 333,
  },
  {
    letters: "קך",
    name: "סדר חדש - למען האזרחים הוותיקים בישראל",
    mandatim: 0,
    percent: "0%",
    amount: 931,
  },
  {
    letters: "קנ",
    name: "כל קול קובע נועם קולמן ולירון עופרי לראשות הממשלה",
    mandatim: 0,
    percent: "0%",
    amount: 1106,
  },
  {
    letters: "קץ",
    name: "באומץ בשבילך",
    mandatim: 0,
    percent: "0%",
    amount: 13075,
  },
  {
    letters: "רז",
    name: "רשימת שלושים/ארבעים בראשות סטלה ויינשטיין",
    mandatim: 0,
    percent: "0%",
    amount: 839,
  },
  {
    letters: "שס",
    name: 'התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ"ל',
    mandatim: 0,
    percent: "0%",
    odafim: "ג",
    amount: 342566,
  },
  {
    letters: "ת",
    name: "דעת טוב ורע וברית שבט אברהם-עלה ירוק ואוסרת אל איסלמיה",
    mandatim: 0,
    percent: "0%",
    amount: 1322,
  },
];
