export const results = [
  {
    letters: "מחל",
    name: "הליכוד בהנהגת בנימין נתניהו לראשות הממשלה",
    mandatim: 0,
    percent: "0%",
    odafim: "ט",
    amount: 1115156,
  },
  {
    letters: "פה",
    name: "יש עתיד בראשות יאיר לפיד לראשות הממשלה",
    mandatim: 0,
    odafim: "כן",
    percent: "0%",
    amount: 847314,
  },
  {
    letters: "ט",
    name: "הציונות הדתית בראשות בצלאל סמוטריץ' ועוצמה יהודית בראשות איתמר בן גביר",
    mandatim: 0,
    percent: "0%",
    odafim: "מחל",
    amount: 516330,
  },
  {
    letters: "כן",
    name: "המחנה הממלכתי בהנהגת בני גנץ לראשות הממשלה",
    mandatim: 0,
    odafim: "פה",
    percent: "0%",
    amount: 432382,
  },
  {
    letters: "שס",
    name: 'התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ"ל',
    mandatim: 0,
    percent: "0%",
    odafim: "ג",
    amount: 392866,
  },
  {
    letters: "ג",
    name: "יהדות התורה והשבת אגודת ישראל – דגל התורה",
    mandatim: 0,
    percent: "0%",
    odafim: "שס",
    amount: 280169,
  },
  {
    letters: "ל",
    name: "ישראל ביתנו בראשות אביגדור ליברמן",
    mandatim: 0,
    percent: "0%",
    amount: 213539,
  },
  {
    letters: "עם",
    name: "הרשימה הערבית המאוחדת",
    mandatim: 0,
    percent: "0%",
    amount: 193995,
  },
  {
    letters: "ום",
    name: 'חד"ש תע"ל בראשות איימן עודה ואחמד טיבי',
    mandatim: 0,
    percent: "0%",
    amount: 178670,
  },
  {
    letters: "אמת",
    name: "מפלגת העבודה בראשות מרב מיכאלי",
    mandatim: 0,
    odafim: "מרצ",
    percent: "0%",
    amount: 175922,
  },
  {
    letters: "מרצ",
    name: "מרצ השמאל של ישראל בראשות זהבה גלאון",
    mandatim: 0,
    odafim: "אמת",
    percent: "0%",
    amount: 150740,
  },
  {
    letters: "ד",
    name: "בל\"ד - אלתג'מוע אלווטני אלדמוקרטי בראשות סמי אבו שחאדה",
    mandatim: 0,
    percent: "0%",
    amount: 138115,
  },
  {
    letters: "ב",
    name: "הבית היהודי בראשות איילת שקד",
    mandatim: 0,
    percent: "0%",
    amount: 56760,
  },
  {
    letters: "אצ",
    name: "חופש כלכלי בראשות אביר קארה",
    mandatim: 0,
    percent: "0%",
    amount: 15807,
  },
  {
    letters: "קץ",
    name: "באומץ בשבילך",
    mandatim: 0,
    percent: "0%",
    amount: 14689,
  },
  {
    letters: "יז",
    name: "הכלכלית החדשה בראשות פרופסור ירון זליכה",
    mandatim: 0,
    percent: "0%",
    amount: 13912,
  },
  {
    letters: "צ",
    name: "צעירים בוערים בהנהגת הדר מוכתר",
    mandatim: 0,
    percent: "0%",
    amount: 8792,
  },
  {
    letters: "ף",
    name: "הפיראטים - הכי טוב לדעתי אני רוצה להיות שם",
    mandatim: 0,
    percent: "0%",
    amount: 1728,
  },
  {
    letters: "ק",
    name: "קול הסביבה והחי",
    mandatim: 0,
    percent: "0%",
    amount: 1618,
  },
  {
    letters: "ת",
    name: "דעת טוב ורע וברית שבט אברהם-עלה ירוק ואוסרת אל איסלמיה",
    mandatim: 0,
    percent: "0%",
    amount: 1549,
  },
  {
    letters: "ני",
    name: "נתיב – נחיה תמיד יחד בכבוד",
    mandatim: 0,
    percent: "0%",
    amount: 1344,
  },
  {
    letters: "קנ",
    name: "כל קול קובע נועם קולמן ולירון עופרי לראשות הממשלה",
    mandatim: 0,
    percent: "0%",
    amount: 1292,
  },
  {
    letters: "ך",
    name: "אני ואתה",
    mandatim: 0,
    percent: "0%",
    amount: 1255,
  },
  {
    letters: "נק",
    name: "יש כיוון בראשות עמוס דב סילבר",
    mandatim: 0,
    percent: "0%",
    amount: 1213,
  },
  {
    letters: "י",
    name: "ישראל חופשית דמוקרטית בראשות אלי אבידר",
    mandatim: 0,
    percent: "0%",
    amount: 1156,
  },
  {
    letters: "קך",
    name: "סדר חדש - למען האזרחים הוותיקים בישראל",
    mandatim: 0,
    percent: "0%",
    amount: 1078,
  },
  {
    letters: "נץ",
    name: "העצמאים החדשים בראשות יורם מועלמי",
    mandatim: 0,
    percent: "0%",
    amount: 1017,
  },
  {
    letters: "ץ",
    name: "מנהיגות חברתית",
    mandatim: 0,
    percent: "0%",
    amount: 987,
  },
  {
    letters: "רז",
    name: "רשימת שלושים/ארבעים בראשות סטלה ויינשטיין",
    mandatim: 0,
    percent: "0%",
    amount: 939,
  },
  {
    letters: "ז",
    name: "שחר כוח חברתי בראשות וג'די טאהר",
    mandatim: 0,
    percent: "0%",
    amount: 431,
  },
  {
    letters: "יק",
    name: 'מפלגת הגוש התנ"כי',
    mandatim: 0,
    percent: "0%",
    amount: 425,
  },
  {
    letters: "קי",
    name: "הלב היהודי בראשות אלי יוסף",
    mandatim: 0,
    percent: "0%",
    amount: 414,
  },
  {
    letters: "נז",
    name: "כבוד האדם, בראשות עו\"ד ארקדי פוגץ'",
    mandatim: 0,
    percent: "0%",
    amount: 362,
  },
  {
    letters: "נר",
    name: '"אנחנו" - בראשות עו"ד מוש חוג\'ה',
    mandatim: 0,
    percent: "0%",
    amount: 334,
  },
  {
    letters: "זץ",
    name: "צומת בראשות משה גרין דרכו של רפול",
    mandatim: 0,
    percent: "0%",
    amount: 292,
  },
  {
    letters: "יץ",
    name: "צו השעה",
    mandatim: 0,
    percent: "0%",
    amount: 264,
  },
  {
    letters: "נף",
    name: "מפלגת שמע בראשות נפתלי גולדמן",
    mandatim: 0,
    percent: "0%",
    amount: 256,
  },
  {
    letters: "ינ",
    name: "איחוד בני הברית – בראשות רב חובל בשארה שליאן",
    mandatim: 0,
    percent: "0%",
    amount: 234,
  },
  {
    letters: "זך",
    name: 'קמ"ה – קידום מעמד הפרט',
    mandatim: 0,
    percent: "0%",
    amount: 204,
  },
];
